// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TSProtocol_v3.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Chat.Protocol
{

    /// <summary>Holder for reflection information generated from TSProtocol_v3.proto</summary>
    public static partial class TSProtocolV3Reflection
    {

        #region Descriptor
        /// <summary>File descriptor for TSProtocol_v3.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static TSProtocolV3Reflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "ChNUU1Byb3RvY29sX3YzLnByb3RvEg1jaGF0LnByb3RvY29sIl0KBlNlbGxl",
                  "chIKCgJpZBgBIAEoCRIRCglmaXJzdE5hbWUYAiABKAkSEAoIbGFzdE5hbWUY",
                  "AyABKAkSEAoIcGFzc3dvcmQYBCABKAkSEAoIdXNlcm5hbWUYBSABKAkiWQoF",
                  "QnV5ZXISCgoCaWQYASABKAkSDAoEaWRBUhgCIAEoCRIRCglmaXJzdE5hbWUY",
                  "AyABKAkSEAoIbGFzdE5hbWUYBCABKAkSEQoJbm9UaWNrZXRzGAUgASgJIoMB",
                  "ChZBcnRpc3RpY1JlcHJlc2VudGF0aW9uEgoKAmlkGAEgASgJEhIKCmFydGlz",
                  "dE5hbWUYAiABKAkSDAoEZGF0YRgDIAEoCRIQCghsb2NhdGlvbhgEIAEoCRIW",
                  "Cg5hdmFpbGFibGVTZWF0cxgFIAEoCRIRCglzb2xkU2VhdHMYBiABKAki5AIK",
                  "CVRTUmVxdWVzdBIrCgR0eXBlGAEgASgOMh0uY2hhdC5wcm90b2NvbC5UU1Jl",
                  "cXVlc3QuVHlwZRInCgZzZWxsZXIYAiABKAsyFS5jaGF0LnByb3RvY29sLlNl",
                  "bGxlckgAEiUKBWJ1eWVyGAMgASgLMhQuY2hhdC5wcm90b2NvbC5CdXllckgA",
                  "EkcKFmFydGlzdGljUmVwcmVzZW50YXRpb24YBCABKAsyJS5jaGF0LnByb3Rv",
                  "Y29sLkFydGlzdGljUmVwcmVzZW50YXRpb25IACKFAQoEVHlwZRILCgdVbmtu",
                  "b3duEAASCQoFTG9naW4QARIKCgZMb2dvdXQQAhIMCghBZGRCdXllchADEg0K",
                  "CUJ1eVRpY2tldBAEEgwKCEdldEFsbEFSEAUSFAoQR2V0QWxsQVJGcm9tRGF0",
                  "ZRAGEhgKFEZpbmRTZWxsZXJCeVVzZXJuYW1lEAdCCQoHcGF5bG9hZCKJAwoK",
                  "VFNSZXNwb25zZRIsCgR0eXBlGAEgASgOMh4uY2hhdC5wcm90b2NvbC5UU1Jl",
                  "c3BvbnNlLlR5cGUSDQoFZXJyb3IYAiABKAkSJQoGc2VsbGVyGAMgASgLMhUu",
                  "Y2hhdC5wcm90b2NvbC5TZWxsZXISIwoFYnV5ZXIYBCABKAsyFC5jaGF0LnBy",
                  "b3RvY29sLkJ1eWVyEkUKFmFydGlzdGljUmVwcmVzZW50YXRpb24YBSADKAsy",
                  "JS5jaGF0LnByb3RvY29sLkFydGlzdGljUmVwcmVzZW50YXRpb24iqgEKBFR5",
                  "cGUSCwoHVW5rbm93bhAAEgYKAk9rEAESCQoFRXJyb3IQAhIJCgVMb2dpbhAD",
                  "EgoKBkxvZ291dBAEEgwKCEFkZEJ1eWVyEAUSDQoJQnV5VGlja2V0EAYSDAoI",
                  "R2V0QWxsQVIQBxIUChBHZXRBbGxBUkZyb21EYXRlEAgSGAoURmluZFNlbGxl",
                  "ckJ5VXNlcm5hbWUQCRIQCgxCb3VnaHRUaWNrZXQQCkIvCiB0aWNrZXQubmV0",
                  "d29yay5wcm90b2J1ZmZwcm90b2NvbEILVFNQcm90b2J1ZnNiBnByb3RvMw=="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { },
                new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.Protocol.Seller), global::Chat.Protocol.Seller.Parser, new[]{ "Id", "FirstName", "LastName", "Password", "Username" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.Protocol.Buyer), global::Chat.Protocol.Buyer.Parser, new[]{ "Id", "IdAR", "FirstName", "LastName", "NoTickets" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.Protocol.ArtisticRepresentation), global::Chat.Protocol.ArtisticRepresentation.Parser, new[]{ "Id", "ArtistName", "Data", "Location", "AvailableSeats", "SoldSeats" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.Protocol.TSRequest), global::Chat.Protocol.TSRequest.Parser, new[]{ "Type", "Seller", "Buyer", "ArtisticRepresentation" }, new[]{ "Payload" }, new[]{ typeof(global::Chat.Protocol.TSRequest.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.Protocol.TSResponse), global::Chat.Protocol.TSResponse.Parser, new[]{ "Type", "Error", "Seller", "Buyer", "ArtisticRepresentation" }, null, new[]{ typeof(global::Chat.Protocol.TSResponse.Types.Type) }, null, null)
                }));
        }
        #endregion

    }
    #region Messages
    public sealed partial class Seller : pb::IMessage<Seller>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<Seller> _parser = new pb::MessageParser<Seller>(() => new Seller());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Seller> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Chat.Protocol.TSProtocolV3Reflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Seller()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Seller(Seller other) : this()
        {
            id_ = other.id_;
            firstName_ = other.firstName_;
            lastName_ = other.lastName_;
            password_ = other.password_;
            username_ = other.username_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Seller Clone()
        {
            return new Seller(this);
        }

        /// <summary>Field number for the "id" field.</summary>
        public const int IdFieldNumber = 1;
        private string id_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Id
        {
            get { return id_; }
            set
            {
                id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "firstName" field.</summary>
        public const int FirstNameFieldNumber = 2;
        private string firstName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string FirstName
        {
            get { return firstName_; }
            set
            {
                firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "lastName" field.</summary>
        public const int LastNameFieldNumber = 3;
        private string lastName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string LastName
        {
            get { return lastName_; }
            set
            {
                lastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "password" field.</summary>
        public const int PasswordFieldNumber = 4;
        private string password_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Password
        {
            get { return password_; }
            set
            {
                password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "username" field.</summary>
        public const int UsernameFieldNumber = 5;
        private string username_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Username
        {
            get { return username_; }
            set
            {
                username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as Seller);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Seller other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Id != other.Id) return false;
            if (FirstName != other.FirstName) return false;
            if (LastName != other.LastName) return false;
            if (Password != other.Password) return false;
            if (Username != other.Username) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Id.Length != 0) hash ^= Id.GetHashCode();
            if (FirstName.Length != 0) hash ^= FirstName.GetHashCode();
            if (LastName.Length != 0) hash ^= LastName.GetHashCode();
            if (Password.Length != 0) hash ^= Password.GetHashCode();
            if (Username.Length != 0) hash ^= Username.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (FirstName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FirstName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(LastName);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Password);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Username);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Id.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteString(Id);
            }
            if (FirstName.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(FirstName);
            }
            if (LastName.Length != 0)
            {
                output.WriteRawTag(26);
                output.WriteString(LastName);
            }
            if (Password.Length != 0)
            {
                output.WriteRawTag(34);
                output.WriteString(Password);
            }
            if (Username.Length != 0)
            {
                output.WriteRawTag(42);
                output.WriteString(Username);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (Id.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
            }
            if (FirstName.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstName);
            }
            if (LastName.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(LastName);
            }
            if (Password.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
            }
            if (Username.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Seller other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Id.Length != 0)
            {
                Id = other.Id;
            }
            if (other.FirstName.Length != 0)
            {
                FirstName = other.FirstName;
            }
            if (other.LastName.Length != 0)
            {
                LastName = other.LastName;
            }
            if (other.Password.Length != 0)
            {
                Password = other.Password;
            }
            if (other.Username.Length != 0)
            {
                Username = other.Username;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            FirstName = input.ReadString();
            break;
          }
          case 26: {
            LastName = input.ReadString();
            break;
          }
          case 34: {
            Password = input.ReadString();
            break;
          }
          case 42: {
            Username = input.ReadString();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            Id = input.ReadString();
                            break;
                        }
                    case 18:
                        {
                            FirstName = input.ReadString();
                            break;
                        }
                    case 26:
                        {
                            LastName = input.ReadString();
                            break;
                        }
                    case 34:
                        {
                            Password = input.ReadString();
                            break;
                        }
                    case 42:
                        {
                            Username = input.ReadString();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class Buyer : pb::IMessage<Buyer>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<Buyer> _parser = new pb::MessageParser<Buyer>(() => new Buyer());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Buyer> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Chat.Protocol.TSProtocolV3Reflection.Descriptor.MessageTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Buyer()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Buyer(Buyer other) : this()
        {
            id_ = other.id_;
            idAR_ = other.idAR_;
            firstName_ = other.firstName_;
            lastName_ = other.lastName_;
            noTickets_ = other.noTickets_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Buyer Clone()
        {
            return new Buyer(this);
        }

        /// <summary>Field number for the "id" field.</summary>
        public const int IdFieldNumber = 1;
        private string id_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Id
        {
            get { return id_; }
            set
            {
                id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "idAR" field.</summary>
        public const int IdARFieldNumber = 2;
        private string idAR_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string IdAR
        {
            get { return idAR_; }
            set
            {
                idAR_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "firstName" field.</summary>
        public const int FirstNameFieldNumber = 3;
        private string firstName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string FirstName
        {
            get { return firstName_; }
            set
            {
                firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "lastName" field.</summary>
        public const int LastNameFieldNumber = 4;
        private string lastName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string LastName
        {
            get { return lastName_; }
            set
            {
                lastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "noTickets" field.</summary>
        public const int NoTicketsFieldNumber = 5;
        private string noTickets_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string NoTickets
        {
            get { return noTickets_; }
            set
            {
                noTickets_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as Buyer);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Buyer other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Id != other.Id) return false;
            if (IdAR != other.IdAR) return false;
            if (FirstName != other.FirstName) return false;
            if (LastName != other.LastName) return false;
            if (NoTickets != other.NoTickets) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Id.Length != 0) hash ^= Id.GetHashCode();
            if (IdAR.Length != 0) hash ^= IdAR.GetHashCode();
            if (FirstName.Length != 0) hash ^= FirstName.GetHashCode();
            if (LastName.Length != 0) hash ^= LastName.GetHashCode();
            if (NoTickets.Length != 0) hash ^= NoTickets.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (IdAR.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(IdAR);
      }
      if (FirstName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FirstName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(LastName);
      }
      if (NoTickets.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(NoTickets);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Id.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteString(Id);
            }
            if (IdAR.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(IdAR);
            }
            if (FirstName.Length != 0)
            {
                output.WriteRawTag(26);
                output.WriteString(FirstName);
            }
            if (LastName.Length != 0)
            {
                output.WriteRawTag(34);
                output.WriteString(LastName);
            }
            if (NoTickets.Length != 0)
            {
                output.WriteRawTag(42);
                output.WriteString(NoTickets);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (Id.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
            }
            if (IdAR.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(IdAR);
            }
            if (FirstName.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstName);
            }
            if (LastName.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(LastName);
            }
            if (NoTickets.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(NoTickets);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Buyer other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Id.Length != 0)
            {
                Id = other.Id;
            }
            if (other.IdAR.Length != 0)
            {
                IdAR = other.IdAR;
            }
            if (other.FirstName.Length != 0)
            {
                FirstName = other.FirstName;
            }
            if (other.LastName.Length != 0)
            {
                LastName = other.LastName;
            }
            if (other.NoTickets.Length != 0)
            {
                NoTickets = other.NoTickets;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            IdAR = input.ReadString();
            break;
          }
          case 26: {
            FirstName = input.ReadString();
            break;
          }
          case 34: {
            LastName = input.ReadString();
            break;
          }
          case 42: {
            NoTickets = input.ReadString();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            Id = input.ReadString();
                            break;
                        }
                    case 18:
                        {
                            IdAR = input.ReadString();
                            break;
                        }
                    case 26:
                        {
                            FirstName = input.ReadString();
                            break;
                        }
                    case 34:
                        {
                            LastName = input.ReadString();
                            break;
                        }
                    case 42:
                        {
                            NoTickets = input.ReadString();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class ArtisticRepresentation : pb::IMessage<ArtisticRepresentation>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<ArtisticRepresentation> _parser = new pb::MessageParser<ArtisticRepresentation>(() => new ArtisticRepresentation());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<ArtisticRepresentation> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Chat.Protocol.TSProtocolV3Reflection.Descriptor.MessageTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ArtisticRepresentation()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ArtisticRepresentation(ArtisticRepresentation other) : this()
        {
            id_ = other.id_;
            artistName_ = other.artistName_;
            data_ = other.data_;
            location_ = other.location_;
            availableSeats_ = other.availableSeats_;
            soldSeats_ = other.soldSeats_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ArtisticRepresentation Clone()
        {
            return new ArtisticRepresentation(this);
        }

        /// <summary>Field number for the "id" field.</summary>
        public const int IdFieldNumber = 1;
        private string id_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Id
        {
            get { return id_; }
            set
            {
                id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "artistName" field.</summary>
        public const int ArtistNameFieldNumber = 2;
        private string artistName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string ArtistName
        {
            get { return artistName_; }
            set
            {
                artistName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "data" field.</summary>
        public const int DataFieldNumber = 3;
        private string data_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Data
        {
            get { return data_; }
            set
            {
                data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "location" field.</summary>
        public const int LocationFieldNumber = 4;
        private string location_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Location
        {
            get { return location_; }
            set
            {
                location_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "availableSeats" field.</summary>
        public const int AvailableSeatsFieldNumber = 5;
        private string availableSeats_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string AvailableSeats
        {
            get { return availableSeats_; }
            set
            {
                availableSeats_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "soldSeats" field.</summary>
        public const int SoldSeatsFieldNumber = 6;
        private string soldSeats_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string SoldSeats
        {
            get { return soldSeats_; }
            set
            {
                soldSeats_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as ArtisticRepresentation);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(ArtisticRepresentation other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Id != other.Id) return false;
            if (ArtistName != other.ArtistName) return false;
            if (Data != other.Data) return false;
            if (Location != other.Location) return false;
            if (AvailableSeats != other.AvailableSeats) return false;
            if (SoldSeats != other.SoldSeats) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Id.Length != 0) hash ^= Id.GetHashCode();
            if (ArtistName.Length != 0) hash ^= ArtistName.GetHashCode();
            if (Data.Length != 0) hash ^= Data.GetHashCode();
            if (Location.Length != 0) hash ^= Location.GetHashCode();
            if (AvailableSeats.Length != 0) hash ^= AvailableSeats.GetHashCode();
            if (SoldSeats.Length != 0) hash ^= SoldSeats.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (ArtistName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ArtistName);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Data);
      }
      if (Location.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Location);
      }
      if (AvailableSeats.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(AvailableSeats);
      }
      if (SoldSeats.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SoldSeats);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Id.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteString(Id);
            }
            if (ArtistName.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(ArtistName);
            }
            if (Data.Length != 0)
            {
                output.WriteRawTag(26);
                output.WriteString(Data);
            }
            if (Location.Length != 0)
            {
                output.WriteRawTag(34);
                output.WriteString(Location);
            }
            if (AvailableSeats.Length != 0)
            {
                output.WriteRawTag(42);
                output.WriteString(AvailableSeats);
            }
            if (SoldSeats.Length != 0)
            {
                output.WriteRawTag(50);
                output.WriteString(SoldSeats);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (Id.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
            }
            if (ArtistName.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(ArtistName);
            }
            if (Data.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
            }
            if (Location.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Location);
            }
            if (AvailableSeats.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(AvailableSeats);
            }
            if (SoldSeats.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(SoldSeats);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(ArtisticRepresentation other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Id.Length != 0)
            {
                Id = other.Id;
            }
            if (other.ArtistName.Length != 0)
            {
                ArtistName = other.ArtistName;
            }
            if (other.Data.Length != 0)
            {
                Data = other.Data;
            }
            if (other.Location.Length != 0)
            {
                Location = other.Location;
            }
            if (other.AvailableSeats.Length != 0)
            {
                AvailableSeats = other.AvailableSeats;
            }
            if (other.SoldSeats.Length != 0)
            {
                SoldSeats = other.SoldSeats;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            ArtistName = input.ReadString();
            break;
          }
          case 26: {
            Data = input.ReadString();
            break;
          }
          case 34: {
            Location = input.ReadString();
            break;
          }
          case 42: {
            AvailableSeats = input.ReadString();
            break;
          }
          case 50: {
            SoldSeats = input.ReadString();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            Id = input.ReadString();
                            break;
                        }
                    case 18:
                        {
                            ArtistName = input.ReadString();
                            break;
                        }
                    case 26:
                        {
                            Data = input.ReadString();
                            break;
                        }
                    case 34:
                        {
                            Location = input.ReadString();
                            break;
                        }
                    case 42:
                        {
                            AvailableSeats = input.ReadString();
                            break;
                        }
                    case 50:
                        {
                            SoldSeats = input.ReadString();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class TSRequest : pb::IMessage<TSRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<TSRequest> _parser = new pb::MessageParser<TSRequest>(() => new TSRequest());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<TSRequest> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Chat.Protocol.TSProtocolV3Reflection.Descriptor.MessageTypes[3]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public TSRequest()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public TSRequest(TSRequest other) : this()
        {
            type_ = other.type_;
            switch (other.PayloadCase)
            {
                case PayloadOneofCase.Seller:
                    Seller = other.Seller.Clone();
                    break;
                case PayloadOneofCase.Buyer:
                    Buyer = other.Buyer.Clone();
                    break;
                case PayloadOneofCase.ArtisticRepresentation:
                    ArtisticRepresentation = other.ArtisticRepresentation.Clone();
                    break;
            }

            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public TSRequest Clone()
        {
            return new TSRequest(this);
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 1;
        private global::Chat.Protocol.TSRequest.Types.Type type_ = global::Chat.Protocol.TSRequest.Types.Type.Unknown;
        /// <summary>
        /// Identifies which request is filled in.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Chat.Protocol.TSRequest.Types.Type Type
        {
            get { return type_; }
            set
            {
                type_ = value;
            }
        }

        /// <summary>Field number for the "seller" field.</summary>
        public const int SellerFieldNumber = 2;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Chat.Protocol.Seller Seller
        {
            get { return payloadCase_ == PayloadOneofCase.Seller ? (global::Chat.Protocol.Seller)payload_ : null; }
            set
            {
                payload_ = value;
                payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Seller;
            }
        }

        /// <summary>Field number for the "buyer" field.</summary>
        public const int BuyerFieldNumber = 3;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Chat.Protocol.Buyer Buyer
        {
            get { return payloadCase_ == PayloadOneofCase.Buyer ? (global::Chat.Protocol.Buyer)payload_ : null; }
            set
            {
                payload_ = value;
                payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Buyer;
            }
        }

        /// <summary>Field number for the "artisticRepresentation" field.</summary>
        public const int ArtisticRepresentationFieldNumber = 4;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Chat.Protocol.ArtisticRepresentation ArtisticRepresentation
        {
            get { return payloadCase_ == PayloadOneofCase.ArtisticRepresentation ? (global::Chat.Protocol.ArtisticRepresentation)payload_ : null; }
            set
            {
                payload_ = value;
                payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ArtisticRepresentation;
            }
        }

        private object payload_;
        /// <summary>Enum of possible cases for the "payload" oneof.</summary>
        public enum PayloadOneofCase
        {
            None = 0,
            Seller = 2,
            Buyer = 3,
            ArtisticRepresentation = 4,
        }
        private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public PayloadOneofCase PayloadCase
        {
            get { return payloadCase_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void ClearPayload()
        {
            payloadCase_ = PayloadOneofCase.None;
            payload_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as TSRequest);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(TSRequest other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Type != other.Type) return false;
            if (!object.Equals(Seller, other.Seller)) return false;
            if (!object.Equals(Buyer, other.Buyer)) return false;
            if (!object.Equals(ArtisticRepresentation, other.ArtisticRepresentation)) return false;
            if (PayloadCase != other.PayloadCase) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Type != global::Chat.Protocol.TSRequest.Types.Type.Unknown) hash ^= Type.GetHashCode();
            if (payloadCase_ == PayloadOneofCase.Seller) hash ^= Seller.GetHashCode();
            if (payloadCase_ == PayloadOneofCase.Buyer) hash ^= Buyer.GetHashCode();
            if (payloadCase_ == PayloadOneofCase.ArtisticRepresentation) hash ^= ArtisticRepresentation.GetHashCode();
            hash ^= (int)payloadCase_;
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Type != global::Chat.Protocol.TSRequest.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Seller) {
        output.WriteRawTag(18);
        output.WriteMessage(Seller);
      }
      if (payloadCase_ == PayloadOneofCase.Buyer) {
        output.WriteRawTag(26);
        output.WriteMessage(Buyer);
      }
      if (payloadCase_ == PayloadOneofCase.ArtisticRepresentation) {
        output.WriteRawTag(34);
        output.WriteMessage(ArtisticRepresentation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Type != global::Chat.Protocol.TSRequest.Types.Type.Unknown)
            {
                output.WriteRawTag(8);
                output.WriteEnum((int)Type);
            }
            if (payloadCase_ == PayloadOneofCase.Seller)
            {
                output.WriteRawTag(18);
                output.WriteMessage(Seller);
            }
            if (payloadCase_ == PayloadOneofCase.Buyer)
            {
                output.WriteRawTag(26);
                output.WriteMessage(Buyer);
            }
            if (payloadCase_ == PayloadOneofCase.ArtisticRepresentation)
            {
                output.WriteRawTag(34);
                output.WriteMessage(ArtisticRepresentation);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (Type != global::Chat.Protocol.TSRequest.Types.Type.Unknown)
            {
                size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Type);
            }
            if (payloadCase_ == PayloadOneofCase.Seller)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Seller);
            }
            if (payloadCase_ == PayloadOneofCase.Buyer)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Buyer);
            }
            if (payloadCase_ == PayloadOneofCase.ArtisticRepresentation)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(ArtisticRepresentation);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(TSRequest other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Type != global::Chat.Protocol.TSRequest.Types.Type.Unknown)
            {
                Type = other.Type;
            }
            switch (other.PayloadCase)
            {
                case PayloadOneofCase.Seller:
                    if (Seller == null)
                    {
                        Seller = new global::Chat.Protocol.Seller();
                    }
                    Seller.MergeFrom(other.Seller);
                    break;
                case PayloadOneofCase.Buyer:
                    if (Buyer == null)
                    {
                        Buyer = new global::Chat.Protocol.Buyer();
                    }
                    Buyer.MergeFrom(other.Buyer);
                    break;
                case PayloadOneofCase.ArtisticRepresentation:
                    if (ArtisticRepresentation == null)
                    {
                        ArtisticRepresentation = new global::Chat.Protocol.ArtisticRepresentation();
                    }
                    ArtisticRepresentation.MergeFrom(other.ArtisticRepresentation);
                    break;
            }

            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Chat.Protocol.TSRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Chat.Protocol.Seller subBuilder = new global::Chat.Protocol.Seller();
            if (payloadCase_ == PayloadOneofCase.Seller) {
              subBuilder.MergeFrom(Seller);
            }
            input.ReadMessage(subBuilder);
            Seller = subBuilder;
            break;
          }
          case 26: {
            global::Chat.Protocol.Buyer subBuilder = new global::Chat.Protocol.Buyer();
            if (payloadCase_ == PayloadOneofCase.Buyer) {
              subBuilder.MergeFrom(Buyer);
            }
            input.ReadMessage(subBuilder);
            Buyer = subBuilder;
            break;
          }
          case 34: {
            global::Chat.Protocol.ArtisticRepresentation subBuilder = new global::Chat.Protocol.ArtisticRepresentation();
            if (payloadCase_ == PayloadOneofCase.ArtisticRepresentation) {
              subBuilder.MergeFrom(ArtisticRepresentation);
            }
            input.ReadMessage(subBuilder);
            ArtisticRepresentation = subBuilder;
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            Type = (global::Chat.Protocol.TSRequest.Types.Type)input.ReadEnum();
                            break;
                        }
                    case 18:
                        {
                            global::Chat.Protocol.Seller subBuilder = new global::Chat.Protocol.Seller();
                            if (payloadCase_ == PayloadOneofCase.Seller)
                            {
                                subBuilder.MergeFrom(Seller);
                            }
                            input.ReadMessage(subBuilder);
                            Seller = subBuilder;
                            break;
                        }
                    case 26:
                        {
                            global::Chat.Protocol.Buyer subBuilder = new global::Chat.Protocol.Buyer();
                            if (payloadCase_ == PayloadOneofCase.Buyer)
                            {
                                subBuilder.MergeFrom(Buyer);
                            }
                            input.ReadMessage(subBuilder);
                            Buyer = subBuilder;
                            break;
                        }
                    case 34:
                        {
                            global::Chat.Protocol.ArtisticRepresentation subBuilder = new global::Chat.Protocol.ArtisticRepresentation();
                            if (payloadCase_ == PayloadOneofCase.ArtisticRepresentation)
                            {
                                subBuilder.MergeFrom(ArtisticRepresentation);
                            }
                            input.ReadMessage(subBuilder);
                            ArtisticRepresentation = subBuilder;
                            break;
                        }
                }
            }
        }
#endif

        #region Nested types
        /// <summary>Container for nested types declared in the TSRequest message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static partial class Types
        {
            public enum Type
            {
                [pbr::OriginalName("Unknown")] Unknown = 0,
                [pbr::OriginalName("Login")] Login = 1,
                [pbr::OriginalName("Logout")] Logout = 2,
                [pbr::OriginalName("AddBuyer")] AddBuyer = 3,
                [pbr::OriginalName("BuyTicket")] BuyTicket = 4,
                [pbr::OriginalName("GetAllAR")] GetAllAr = 5,
                [pbr::OriginalName("GetAllARFromDate")] GetAllArfromDate = 6,
                [pbr::OriginalName("FindSellerByUsername")] FindSellerByUsername = 7,
            }

        }
        #endregion

    }

    public sealed partial class TSResponse : pb::IMessage<TSResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<TSResponse> _parser = new pb::MessageParser<TSResponse>(() => new TSResponse());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<TSResponse> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Chat.Protocol.TSProtocolV3Reflection.Descriptor.MessageTypes[4]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public TSResponse()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public TSResponse(TSResponse other) : this()
        {
            type_ = other.type_;
            error_ = other.error_;
            seller_ = other.seller_ != null ? other.seller_.Clone() : null;
            buyer_ = other.buyer_ != null ? other.buyer_.Clone() : null;
            artisticRepresentation_ = other.artisticRepresentation_.Clone();
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public TSResponse Clone()
        {
            return new TSResponse(this);
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 1;
        private global::Chat.Protocol.TSResponse.Types.Type type_ = global::Chat.Protocol.TSResponse.Types.Type.Unknown;
        /// <summary>
        /// Identifies which request is filled in.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Chat.Protocol.TSResponse.Types.Type Type
        {
            get { return type_; }
            set
            {
                type_ = value;
            }
        }

        /// <summary>Field number for the "error" field.</summary>
        public const int ErrorFieldNumber = 2;
        private string error_ = "";
        /// <summary>
        /// One of the following will be filled in, depending on the type.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Error
        {
            get { return error_; }
            set
            {
                error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "seller" field.</summary>
        public const int SellerFieldNumber = 3;
        private global::Chat.Protocol.Seller seller_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Chat.Protocol.Seller Seller
        {
            get { return seller_; }
            set
            {
                seller_ = value;
            }
        }

        /// <summary>Field number for the "buyer" field.</summary>
        public const int BuyerFieldNumber = 4;
        private global::Chat.Protocol.Buyer buyer_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Chat.Protocol.Buyer Buyer
        {
            get { return buyer_; }
            set
            {
                buyer_ = value;
            }
        }

        /// <summary>Field number for the "artisticRepresentation" field.</summary>
        public const int ArtisticRepresentationFieldNumber = 5;
        private static readonly pb::FieldCodec<global::Chat.Protocol.ArtisticRepresentation> _repeated_artisticRepresentation_codec
            = pb::FieldCodec.ForMessage(42, global::Chat.Protocol.ArtisticRepresentation.Parser);
        private readonly pbc::RepeatedField<global::Chat.Protocol.ArtisticRepresentation> artisticRepresentation_ = new pbc::RepeatedField<global::Chat.Protocol.ArtisticRepresentation>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::Chat.Protocol.ArtisticRepresentation> ArtisticRepresentation
        {
            get { return artisticRepresentation_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as TSResponse);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(TSResponse other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Type != other.Type) return false;
            if (Error != other.Error) return false;
            if (!object.Equals(Seller, other.Seller)) return false;
            if (!object.Equals(Buyer, other.Buyer)) return false;
            if (!artisticRepresentation_.Equals(other.artisticRepresentation_)) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Type != global::Chat.Protocol.TSResponse.Types.Type.Unknown) hash ^= Type.GetHashCode();
            if (Error.Length != 0) hash ^= Error.GetHashCode();
            if (seller_ != null) hash ^= Seller.GetHashCode();
            if (buyer_ != null) hash ^= Buyer.GetHashCode();
            hash ^= artisticRepresentation_.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Type != global::Chat.Protocol.TSResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (seller_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Seller);
      }
      if (buyer_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Buyer);
      }
      artisticRepresentation_.WriteTo(output, _repeated_artisticRepresentation_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Type != global::Chat.Protocol.TSResponse.Types.Type.Unknown)
            {
                output.WriteRawTag(8);
                output.WriteEnum((int)Type);
            }
            if (Error.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(Error);
            }
            if (seller_ != null)
            {
                output.WriteRawTag(26);
                output.WriteMessage(Seller);
            }
            if (buyer_ != null)
            {
                output.WriteRawTag(34);
                output.WriteMessage(Buyer);
            }
            artisticRepresentation_.WriteTo(ref output, _repeated_artisticRepresentation_codec);
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (Type != global::Chat.Protocol.TSResponse.Types.Type.Unknown)
            {
                size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Type);
            }
            if (Error.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
            }
            if (seller_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Seller);
            }
            if (buyer_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Buyer);
            }
            size += artisticRepresentation_.CalculateSize(_repeated_artisticRepresentation_codec);
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(TSResponse other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Type != global::Chat.Protocol.TSResponse.Types.Type.Unknown)
            {
                Type = other.Type;
            }
            if (other.Error.Length != 0)
            {
                Error = other.Error;
            }
            if (other.seller_ != null)
            {
                if (seller_ == null)
                {
                    Seller = new global::Chat.Protocol.Seller();
                }
                Seller.MergeFrom(other.Seller);
            }
            if (other.buyer_ != null)
            {
                if (buyer_ == null)
                {
                    Buyer = new global::Chat.Protocol.Buyer();
                }
                Buyer.MergeFrom(other.Buyer);
            }
            artisticRepresentation_.Add(other.artisticRepresentation_);
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Chat.Protocol.TSResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (seller_ == null) {
              Seller = new global::Chat.Protocol.Seller();
            }
            input.ReadMessage(Seller);
            break;
          }
          case 34: {
            if (buyer_ == null) {
              Buyer = new global::Chat.Protocol.Buyer();
            }
            input.ReadMessage(Buyer);
            break;
          }
          case 42: {
            artisticRepresentation_.AddEntriesFrom(input, _repeated_artisticRepresentation_codec);
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            Type = (global::Chat.Protocol.TSResponse.Types.Type)input.ReadEnum();
                            break;
                        }
                    case 18:
                        {
                            Error = input.ReadString();
                            break;
                        }
                    case 26:
                        {
                            if (seller_ == null)
                            {
                                Seller = new global::Chat.Protocol.Seller();
                            }
                            input.ReadMessage(Seller);
                            break;
                        }
                    case 34:
                        {
                            if (buyer_ == null)
                            {
                                Buyer = new global::Chat.Protocol.Buyer();
                            }
                            input.ReadMessage(Buyer);
                            break;
                        }
                    case 42:
                        {
                            artisticRepresentation_.AddEntriesFrom(ref input, _repeated_artisticRepresentation_codec);
                            break;
                        }
                }
            }
        }
#endif

        #region Nested types
        /// <summary>Container for nested types declared in the TSResponse message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static partial class Types
        {
            public enum Type
            {
                [pbr::OriginalName("Unknown")] Unknown = 0,
                [pbr::OriginalName("Ok")] Ok = 1,
                [pbr::OriginalName("Error")] Error = 2,
                [pbr::OriginalName("Login")] Login = 3,
                [pbr::OriginalName("Logout")] Logout = 4,
                [pbr::OriginalName("AddBuyer")] AddBuyer = 5,
                [pbr::OriginalName("BuyTicket")] BuyTicket = 6,
                [pbr::OriginalName("GetAllAR")] GetAllAr = 7,
                [pbr::OriginalName("GetAllARFromDate")] GetAllArfromDate = 8,
                [pbr::OriginalName("FindSellerByUsername")] FindSellerByUsername = 9,
                [pbr::OriginalName("BoughtTicket")] BoughtTicket = 10,
            }

        }
        #endregion

    }

    #endregion

}

#endregion Designer generated code
